name: publish from habitat target file

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag for releases'
        required: true
        type: string
      habitat-target-files:
        description: 'habitat target name, split by comma. (e.g. cmake)'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: run habitat sync
        run: |
          curl -L https://github.com/lynx-infra/habitat/releases/latest/download/hab.pex -o hab.pex
          chmod +x hab.pex
          ./hab.pex sync . --target ${{github.event.inputs.habitat-target-files}} --target-only

      - name: generate sha256 list
        run: python3 publish_helper.py --sha256-list

      - name: push to release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          bodyFile: "hash.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "buildtools-*.tar.gz"
